"""drop is_blocked column from users

Revision ID: 6e177ba42dbf
Revises: add_admin_fields
Create Date: 2026-04-09 21:50:00.685374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e177ba42dbf'
down_revision: Union[str, Sequence[str], None] = 'add_admin_fields'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_blocked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_blocked', sa.BOOLEAN(), server_default=sa.text("'0'"), nullable=False))
    # ### end Alembic commands ###
