"""add is_admin and is_blocked fields to users

Revision ID: add_admin_fields
Revises: 0513b209aa1d
Create Date: 2026-04-09 11:44:00.000000

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'add_admin_fields'
down_revision: str | Sequence[str] | None = '0513b209aa1d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_blocked')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
